#!/usr/bin/env python3
"""
Tradutor local PT-BR → EN do gêmeo digital `/en/` — custo zero de token.

Nenhuma chamada de API de LLM. O motor é o Argos Translate (NMT open-source,
CTranslate2) rodando na máquina de build. Ver `scripts/i18n/README.md` para a
instalação e `docs/specs/pages/SDD-i18n-en.md` para o contrato de escopo.

Uso:
  python3 scripts/i18n/translate.py --install-model     # passo de rede, 1x
  python3 scripts/i18n/translate.py --all               # espelha tudo
  python3 scripts/i18n/translate.py src/proposta.html   # espelha um arquivo
  python3 scripts/i18n/translate.py --all --engine identity   # só estrutura
  python3 scripts/i18n/translate.py --print-map         # mapa PT→EN em JSON

`--engine identity` não traduz: aplica só as transformações estruturais (lang,
hreflang, canonical, rotas, `inLanguage`). É o que permite exercitar o
pipeline inteiro num CI sem baixar o modelo.

Saída: 0 sucesso · 1 falha · 2 motor indisponível.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import assets  # noqa: E402
import engine as engine_mod  # noqa: E402
from html_tx import translate_html  # noqa: E402
from jsonld_tx import translate_json_data  # noqa: E402
from markdown_tx import translate_markdown  # noqa: E402

#: O aviso de proveniência vai em inglês porque mora num arquivo em inglês —
#: quem abre `src/en/proposta.html` é quem precisa ler que aquilo é gerado.
AVISO = (
    "<!-- Generated by scripts/i18n/translate.py from {origem}. "
    "Do not edit by hand: the next sync overwrites it. -->\n"
)


def traduz_ativo(ativo: assets.Asset, motor) -> str:
    bruto = ativo.source.read_text(encoding="utf-8")

    if ativo.kind == "html":
        corpo = translate_html(bruto, motor, ativo.route_pt, ativo.route_en)
        return _prefixa_aviso(corpo, AVISO.format(origem=ativo.rel_source))

    if ativo.kind == "json":
        # JSON não aceita comentário: a proveniência fica no manifesto.
        return translate_json_data(bruto, motor)

    corpo = translate_markdown(bruto, motor, base="public/en")
    if ativo.kind == "aeo":
        # `llms.txt` tem de começar pelo H1 (llmstxt.org). Um comentário antes
        # dele quebra o parse de quem lê o arquivo ao pé da letra — e quem lê
        # `llms.txt` é exatamente esse tipo de leitor.
        return corpo
    return AVISO.format(origem=ativo.rel_source) + corpo


def _prefixa_aviso(html: str, aviso: str) -> str:
    """Coloca o aviso depois do doctype — antes dele alguns validadores reclamam."""
    baixo = html.lstrip().lower()
    if baixo.startswith("<!doctype"):
        fim = html.index(">", html.lower().index("<!doctype")) + 1
        return f"{html[:fim]}\n{aviso.rstrip()}{html[fim:]}"
    return aviso + html


def escreve(ativo: assets.Asset, conteudo: str, out_root: Path | None) -> None:
    """
    `out_root` redireciona só a ESCRITA, mantendo o caminho relativo.

    Serve aos testes: `tests/i18n.test.mjs` gera os espelhos num diretório
    temporário e afere as invariantes de estrutura sem depender de nada
    versionado nem sujar a árvore de trabalho.
    """
    destino = ativo.target if out_root is None else out_root / ativo.rel_target
    destino.parent.mkdir(parents=True, exist_ok=True)
    destino.write_text(conteudo, encoding="utf-8")


def seleciona(args) -> list[assets.Asset]:
    todos = assets.all_assets()
    if args.all:
        return todos
    if not args.arquivos:
        return []
    pedidos = set()
    for bruto in args.arquivos:
        caminho = Path(bruto)
        caminho = caminho if caminho.is_absolute() else (assets.ROOT / caminho)
        pedidos.add(caminho.resolve())
    return [a for a in todos if a.source.resolve() in pedidos]


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Espelha ativos públicos PT-BR em /en/ via Argos Translate."
    )
    ap.add_argument("arquivos", nargs="*", help="caminhos PT-BR a espelhar")
    ap.add_argument("--all", action="store_true", help="espelha todo o escopo público")
    ap.add_argument(
        "--engine",
        default="argos",
        choices=tuple(engine_mod.MOTORES),
        help=(
            "argos = tradução real; identity = só transformação estrutural; "
            "mock/mangle = motores de teste (ver engine.py)"
        ),
    )
    ap.add_argument("--install-model", action="store_true", help="baixa o modelo pt→en")
    ap.add_argument("--print-map", action="store_true", help="imprime o mapa PT→EN")
    ap.add_argument(
        "--out-root",
        metavar="DIR",
        help="grava os espelhos sob DIR em vez da árvore do repositório (testes)",
    )
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if args.print_map:
        print(assets.as_json())
        return 0

    if args.install_model:
        try:
            caminho = engine_mod.install_model()
        except engine_mod.TranslationUnavailable as exc:
            print(f"[i18n] {exc}", file=sys.stderr)
            return 2
        print(f"[i18n] modelo pt→en instalado ({caminho}).")
        return 0

    alvos = seleciona(args)
    if not alvos:
        if args.arquivos:
            # Não é erro: editar `.claude/` ou `docs/specs/` não gera espelho.
            if not args.quiet:
                print("[i18n] nenhum dos arquivos indicados está no escopo público.")
            return 0
        ap.error("informe arquivos, --all, --print-map ou --install-model")

    try:
        motor = engine_mod.get_engine(args.engine)
    except engine_mod.TranslationUnavailable as exc:
        print(f"[i18n] {exc}", file=sys.stderr)
        return 2

    out_root = Path(args.out_root).resolve() if args.out_root else None
    inicio = time.time()
    falhas = 0
    for ativo in alvos:
        try:
            escreve(ativo, traduz_ativo(ativo, motor), out_root)
        except Exception as exc:  # noqa: BLE001 - um arquivo ruim não para a fila
            falhas += 1
            print(f"[i18n] ERRO em {ativo.rel_source}: {exc}", file=sys.stderr)
            continue
        if not args.quiet:
            print(f"[i18n] {ativo.rel_source} → {ativo.rel_target}")

    engine_mod.flush_cache()
    if not args.quiet:
        print(
            f"[i18n] {len(alvos) - falhas}/{len(alvos)} ativos em "
            f"{time.time() - inicio:.1f}s · motor={motor.name} "
            f"· segmentos={motor.calls} cache={motor.cache_hits} "
            f"contingências={motor.fallbacks}"
        )
    return 1 if falhas else 0


if __name__ == "__main__":
    raise SystemExit(main())
