// Fonte única de conteúdo AEO/GEO por página. Editar aqui → reexecutar
// build-aeo.mjs / gen-og.mjs propaga para todas as páginas.
// Campos: slug, type (schema), tier, title, headline?, description, datas,
// section, tags[], keywords[], about[], mentions[], teaches[], audience,
// citation[], tldr{heading,lede,points[],foot}, faq[{q,a}], terms[{slug,name,def}],
// mdSections[{h,body}], og{eyebrow,title('{x}'=gradiente),subtitle,thesis,chips[]},
// hasMd, ogType, ogTitle, ogDescription, video.

export const PAGES = [
  // ===================================================================== TIER S
  {
    slug: 'engenharia-agentes-ia', type: 'TechArticle', tier: 'S', hasMd: true,
    title: 'Engenharia de Agentes de IA — Os 10 princípios do determinismo',
    headline: 'Engenharia de Agentes de IA: dez princípios para sistemas confiáveis',
    description: 'Os dez princípios de engenharia que tornam agentes de IA confiáveis: determinístico-primeiro, Cérebro × Vitrine, contratos rígidos, Limiar de Certeza, FinOps por ledger e o MCP como fronteira.',
    datePublished: '2026-06-10', dateModified: '2026-06-21',
    section: 'Engenharia de IA',
    tags: ['Engenharia de Agentes', 'Determinismo', 'MCP', 'FinOps de IA', 'Governança de IA'],
    keywords: ['engenharia de agentes de IA', 'determinístico-primeiro', 'Cérebro e Vitrine', 'contrato rígido', 'Limiar de Certeza', 'Model Context Protocol', 'MCP', 'ledger de quota', 'FinOps de IA', 'open-world', 'fail-closed', 'governança de IA'],
    about: [
      { name: 'Engenharia de Agentes de IA' }, { name: 'Determinístico-primeiro' },
      { name: 'Model Context Protocol', sameAs: 'https://modelcontextprotocol.io' },
      { name: 'FinOps de IA' }, { name: 'Governança de IA' },
    ],
    audience: 'Líderes de Engenharia, Arquitetos de Soluções, Tech Leads, Engenheiros de IA',
    tldr: {
      heading: 'O que é Engenharia de Agentes de IA',
      lede: '**Engenharia de Agentes de IA** é a disciplina de construir sistemas agênticos confiáveis tratando a saída do modelo como **input não confiável** governado por arquitetura. A regra central: um sistema de IA confiável tem **muito pouca IA no caminho crítico** — regras e dados resolvem o determinístico e o modelo atua só no resíduo interpretativo.',
      points: [
        '**Determinístico-primeiro** — resolva com regras e dados; gaste IA só onde o modelo é insubstituível.',
        '**Cérebro × Vitrine** — separe motor cognitivo (sensível) da interface (exposta) por um contrato estreito.',
        '**Contratos rígidos + Limiar de Certeza** — schema estrito rejeita campos inesperados e confiança abaixo do piso; fail-closed.',
        '**MCP + FinOps por ledger** — fronteira de ferramentas controlada e quota que recusa o gasto antes do provedor.',
      ],
      foot: 'É o pilar **M2 (Arquitetar)** da [Engenharia da Confiança](/engenharia-confianca).',
    },
    faq: [
      { q: 'O que é Engenharia de Agentes de IA?', a: 'É a disciplina de projetar sistemas agênticos confiáveis tratando cada saída do modelo como input não confiável, validado por arquitetura (schemas, limiares, fronteiras). O objetivo é manter pouca IA no caminho crítico: regras e dados resolvem o determinístico e o LLM atua apenas no resíduo interpretativo.' },
      { q: 'O que significa "determinístico-primeiro"?', a: 'Resolver com regras e dados estruturados tudo o que for possível e reservar a IA só para a fração da tarefa que exige o modelo. Mesma entrada deve produzir mesma saída; o não-determinismo fica isolado e testável.' },
      { q: 'O que é a separação Cérebro × Vitrine?', a: 'O motor cognitivo (pesado, com acesso a dados sensíveis) e a interface exposta são sistemas separados, ligados por um contrato estreito. A Vitrine nunca toca o banco diretamente; o Cérebro nunca confia cegamente no que vem de fora — reduz a superfície de ataque e de falha.' },
      { q: 'O que é o Limiar de Certeza e o fail-closed?', a: 'Toda inferência carrega um grau de confiança; a arquitetura define um piso abaixo do qual a saída é interceptada antes de virar fato e degradada para um fallback estruturado (revisão humana, incerteza explícita ou rota determinística). Se não foi possível concluir com segurança, o sistema para num ponto seguro em vez de promover um palpite.' },
      { q: 'Qual o papel do MCP (Model Context Protocol)?', a: 'O MCP é a fronteira de segurança pela qual o agente ganha "mãos e olhos" de forma controlada, declarando explicitamente quais ferramentas pode usar. Cada tool é tipada por um schema com pré e pós-condições, o que torna as ações do agente auditáveis.' },
      { q: 'Como controlar custo (FinOps) em agentes de IA?', a: 'Com um ledger de quota: um estado de domínio persistente que governa créditos e gasto e recusa a despesa antes mesmo de chamar o provedor. Combinado com poda precoce (filtro barato primeiro), evita que o custo de chamadas a modelos escape do controle.' },
    ],
    terms: [
      { slug: 'determinismo-primeiro', name: 'Determinístico-primeiro', def: 'Resolver com regras e dados; gastar IA apenas no resíduo interpretativo.' },
      { slug: 'cerebro-vitrine', name: 'Cérebro × Vitrine', def: 'Separação entre motor cognitivo (sensível) e interface (exposta), ligados por contrato estreito.' },
      { slug: 'contrato-rigido', name: 'Contrato rígido (schema)', def: 'Esquema estrito que rejeita campos inesperados e inferências abaixo do Limiar de Certeza.' },
      { slug: 'limiar-certeza', name: 'Limiar de Certeza', def: 'Piso de confiança abaixo do qual a inferência é interceptada e degradada para fallback estruturado.' },
      { slug: 'mcp', name: 'MCP (Model Context Protocol)', def: 'Protocolo que dá ao agente ferramentas controladas e declaradas (fronteira de segurança).' },
      { slug: 'ledger-quota', name: 'Ledger de quota', def: 'Estado persistente que governa gasto/créditos e recusa a despesa antes do provedor (FinOps).' },
      { slug: 'open-world', name: 'Open-World', def: 'Ausência de dado é incerteza explícita, nunca "falso".' },
      { slug: 'fail-closed', name: 'Fail-closed', def: 'Se não foi possível concluir com segurança, para-se num ponto seguro em vez de promover um palpite.' },
    ],
    mdSections: [
      { h: 'O princípio invariante', body: 'Um sistema de IA confiável tem muito pouca IA no caminho crítico. A confiança não nasce de um prompt mais inteligente, e sim de arquitetura mais disciplinada: regras e dados resolvem o determinístico e o modelo é chamado apenas no resíduo interpretativo, sob contratos que tornam sua saída auditável.' },
      { h: 'As fronteiras', body: 'Contratos rígidos em toda fronteira transformam a saída probabilística do LLM em input validado. O MCP padroniza as ferramentas do agente; o ledger de quota governa o custo; o Limiar de Certeza com fail-closed garante que nada abaixo do piso de confiança vire fato.' },
    ],
    og: {
      eyebrow: 'Engenharia de IA · 10 princípios',
      title: 'Engenharia de {Agentes de IA}',
      subtitle: 'Os princípios do determinismo: contratos, MCP e FinOps',
      thesis: 'A capacidade vem do modelo; a confiança vem da engenharia.',
      chips: [{ k: '01', label: 'Determinismo' }, { k: '02', label: 'Cérebro×Vitrine' }, { k: '03', label: 'Contratos' }, { k: '04', label: 'MCP' }],
    },
  },

  {
    slug: 'devin', type: 'TechArticle', tier: 'S', hasMd: true,
    title: 'Vibe Coding com Devin — De Executor a Orquestrador Cognitivo',
    headline: 'Vibe Coding com Devin: Agent-Driven Development na prática',
    description: 'Como o Vibe Coding maduro vira engenharia: Spec-Driven Development, testes BDD, o arsenal Skills/Playbooks/Knowledge e a renderização governada (A2UI) — do estudo de caso Devin + Salesforce.',
    datePublished: '2026-05-19', dateModified: '2026-06-21',
    section: 'Agent-Driven Development',
    tags: ['Vibe Coding', 'Spec-Driven Development', 'Devin', 'A2UI', 'BDD'],
    keywords: ['Vibe Coding', 'Devin', 'Agent-Driven Development', 'Spec-Driven Development', 'SDD', 'BDD', 'Skills Playbooks Knowledge', 'A2UI', 'Orquestrador Cognitivo', 'Salesforce'],
    about: [
      { name: 'Vibe Coding' }, { name: 'Spec-Driven Development' }, { name: 'Agent-Driven Development' },
      { name: 'A2UI (Agent-to-User Interface)' }, { name: 'Behavior-Driven Development' },
    ],
    audience: 'Tech Leads, Engenheiros de Software, Líderes de Engenharia',
    tldr: {
      heading: 'O que é Vibe Coding com Devin',
      lede: 'O **Vibe Coding** maduro não é caos de prompts: é **intenção estruturada e persistente**. O humano sobe de executor a **Orquestrador Cognitivo** — dirige a inteligência da máquina com intenção clara, como um chef executivo que garante que cada prato saia certo sem cozinhar todos.',
      points: [
        '**Spec-Driven Development (SDD)** — a especificação versionada é a fonte da verdade; a IA implementa contra ela.',
        '**BDD como alvo** — cenários Dado/Quando/Então provam que a intenção foi cumprida.',
        '**Arsenal Skills · Playbooks · Knowledge** — conhecimento organizacional que acumula e se reusa no Git.',
        '**A2UI** — o agente emite intenção de interface; a renderização é governada e determinística.',
      ],
      foot: 'É o pilar **M0/M3 (Despertar/Orquestrar)** da [Engenharia da Confiança](/engenharia-confianca).',
    },
    faq: [
      { q: 'O que é Vibe Coding?', a: 'Vibe Coding é desenvolver software dirigindo um agente de IA por intenção em vez de digitar cada linha. Na forma madura, a intenção é estruturada e persistente (uma especificação versionada), não um prompt efêmero — é o que separa o experimento do método.' },
      { q: 'O que é Spec-Driven Development (SDD)?', a: 'No SDD a especificação é a fonte da verdade: escreve-se o quê e o porquê, e a IA implementa contra a spec com testes (BDD) como alvo objetivo. Quando a intenção vive num prompt descartável ela se perde; quando vive numa spec no repositório, ela escala e é auditável.' },
      { q: 'O que é o Orquestrador Cognitivo?', a: 'É o profissional que dirige a inteligência da máquina com intenção — define o quê e o porquê e julga o resultado — em vez de executar cada linha. Ele consome ferramentas tipadas derivadas de schemas e versiona não só o código, mas o raciocínio que o produziu.' },
      { q: 'O que são Skills, Playbooks e Knowledge?', a: 'É o arsenal de inteligência organizacional que cresce com o tempo: Skills são procedimentos reutilizáveis (refatorar sem risco, testar de forma exaustiva), Playbooks são receitas de processo (code review, onboarding, migração) e Knowledge é o ativo que acumula (arquitetura, convenções, lições e gotchas).' },
      { q: 'O que é A2UI (Agent-to-User Interface)?', a: 'É a evolução do MCP da consulta para a renderização: o agente usa o protocolo para emitir intenção de interface — o Cérebro decide o quê mostrar (dados sob contrato) e a Vitrine determinística decide como renderizar. A interface deixa de ser texto livre imprevisível e passa a ser output governado, testável e reproduzível.' },
    ],
    terms: [
      { slug: 'vibe-coding', name: 'Vibe Coding', def: 'Desenvolver dirigindo um agente por intenção; na forma madura, intenção estruturada e persistente.' },
      { slug: 'sdd', name: 'SDD (Spec-Driven Development)', def: 'A especificação como fonte da verdade; a IA implementa contra a spec, com testes como alvo.' },
      { slug: 'bdd', name: 'BDD', def: 'Cenários Dado/Quando/Então com fixtures gravadas; testa o sistema ao redor do modelo.' },
      { slug: 'orquestrador-cognitivo', name: 'Orquestrador Cognitivo', def: 'Quem dirige a inteligência da máquina com intenção, em vez de executar cada linha.' },
      { slug: 'a2ui', name: 'A2UI (Agent-to-User Interface)', def: 'O agente emite intenção de interface; a Vitrine determinística decide como renderizar.' },
    ],
    mdSections: [
      { h: 'O fluxo prático', body: 'Validado no estudo de caso Devin + Salesforce, o fluxo tem quatro passos: Spec (definição SDD do comportamento) → Retrieve (descoberta autônoma de contexto) → Refatorar (edição guiada pela spec) → Validar (Apex Tests que provam a intenção). A spec é o As-Is/To-Be tornado executável, sob os contratos da camada de arquitetura.' },
    ],
    og: {
      eyebrow: 'Agent-Driven Development',
      title: 'Vibe Coding com {Devin}',
      subtitle: 'De Executor a Orquestrador Cognitivo',
      thesis: 'A intenção versionada escala; o prompt efêmero se perde.',
      chips: [{ k: 'SPEC', label: 'SDD' }, { k: 'BDD', label: 'Validação' }, { k: 'ARSENAL', label: 'Skills/Playbooks' }, { k: 'A2UI', label: 'Renderização' }],
    },
  },

  {
    slug: 'proposta-engenharia-reversa', type: 'TechArticle', tier: 'S', hasMd: true,
    title: 'Engenharia Reversa Assistida por IA — Mapear a Verdade do Legado',
    headline: 'Engenharia Reversa Assistida por IA: congelar o As-Is com fidelidade',
    description: 'Antes de modernizar, congele o As-Is. Como a engenharia reversa assistida por IA revela o conhecimento tribal de sistemas legados via Matriz de Evidências e Inventário de Comportamentos.',
    datePublished: '2026-05-01', dateModified: '2026-06-21',
    section: 'Modernização de Legado',
    tags: ['Engenharia Reversa', 'Salesforce', 'As-Is To-Be', 'Modernização', 'Legado'],
    keywords: ['engenharia reversa assistida por IA', 'As-Is To-Be', 'Matriz de Evidências', 'Inventário de Comportamentos', 'conhecimento tribal', 'modernização de legado', 'Salesforce', 'Apex', 'Flows'],
    about: [
      { name: 'Engenharia Reversa assistida por IA' }, { name: 'Matriz de Evidências' },
      { name: 'Inventário de Comportamentos' }, { name: 'Modernização de Legado' },
    ],
    audience: 'Arquitetos de Soluções, Tech Leads, Líderes de Transformação Digital',
    tldr: {
      heading: 'O que é Engenharia Reversa Assistida por IA',
      lede: 'Antes de modernizar (To-Be), é preciso **congelar uma fotografia de alta fidelidade do que o sistema realmente faz hoje (As-Is)**. O conhecimento crítico costuma viver escondido — em Apex, em Flows fragmentados e na cabeça de poucos. Modernizar sem mapear é apagar regras vitais sem saber.',
      points: [
        '**Descoberta guiada por jornadas** — parte-se de uma jornada de negócio e segue-se a trilha de execução, isolando o código morto.',
        '**Matriz de Evidências** — cruza insumos estrutural, de estado, operacional e humano para evitar falsos-positivos.',
        '**Inventário de Comportamentos** — regras core, efeitos colaterais e workarounds, classificados por confiança.',
        '**As-Is → contratos** — o inventário auditado vira a matéria-prima dos schemas de validação.',
      ],
      foot: 'É o pilar **M1 (Mapear)** da [Engenharia da Confiança](/engenharia-confianca).',
    },
    faq: [
      { q: 'O que é engenharia reversa assistida por IA?', a: 'É o uso de IA para revelar e congelar, com alta fidelidade, o comportamento real de um sistema legado (o As-Is) antes de modernizá-lo. O objetivo não é gerar documentação eterna, e sim um inventário auditável para que arquitetos decidam o que preservar, redesenhar ou descontinuar.' },
      { q: 'Por que congelar o As-Is antes de modernizar?', a: 'Porque todo sistema legado sofre de "conhecimento tribal": regras que sustentam o negócio mas que ninguém escreveu. Modernizar sem mapear apaga regras vitais sem saber — o As-Is de alta fidelidade é a rede de segurança da transformação.' },
      { q: 'Qual a melhor estratégia de descoberta?', a: 'A descoberta guiada por jornadas críticas e risco (top-down com deep dive): parte-se de uma jornada de negócio, segue-se a trilha de execução (call stack) e mapeia-se todo componente que ela toca. Isso isola rapidamente o código morto, que não pertence a jornada nenhuma.' },
      { q: 'O que é a Matriz de Evidências?', a: 'É um pool multifacetado que evita falsos-positivos: insumos estruturais (metadados, Apex, Flows), de estado (Custom Metadata/Settings), operacionais (Event Monitoring, Debug Logs, que revelam o código zumbi) e humanos (commits, tickets, entrevistas, que dão o porquê da regra).' },
      { q: 'O que é o Inventário de Comportamentos?', a: 'É o ativo final do mapeamento: não um catálogo de IFs/ELSEs, mas regras core, efeitos colaterais e workarounds históricos, cada um classificado pela confiança da evidência. Ele é a matéria-prima dos contratos de validação da fase seguinte.' },
    ],
    terms: [
      { slug: 'as-is', name: 'As-Is', def: 'Fotografia de alta fidelidade do que o sistema realmente faz hoje, antes de modernizar.' },
      { slug: 'matriz-evidencias', name: 'Matriz de Evidências', def: 'Pool multifacetado (estrutural, estado, operacional, humano) que evita falsos-positivos na descoberta.' },
      { slug: 'inventario-comportamentos', name: 'Inventário de Comportamentos', def: 'Regras core, efeitos colaterais e workarounds do As-Is, classificados por confiança da evidência.' },
      { slug: 'conhecimento-tribal', name: 'Conhecimento tribal', def: 'Regras que sustentam o negócio mas que ninguém documentou; vivem na cabeça de poucos.' },
    ],
    mdSections: [
      { h: 'Do passado ao futuro', body: 'O objetivo da engenharia reversa assistida por IA não é gerar documentação viva eterna — é congelar o As-Is com fidelidade suficiente para que arquitetos decidam, de forma auditável, o que preservar, redesenhar ou descontinuar. Cada regra catalogada vira, depois, uma cláusula nos schemas de validação.' },
    ],
    og: {
      eyebrow: 'Modernização de Legado',
      title: 'Engenharia {Reversa} Assistida por IA',
      subtitle: 'Mapear a verdade do legado antes de modernizar',
      thesis: 'Modernizar sem mapear é apagar regras vitais sem saber.',
      chips: [{ k: 'AS-IS', label: 'Congelar' }, { k: 'EVID.', label: 'Matriz' }, { k: 'INV.', label: 'Comportamentos' }, { k: 'TO-BE', label: 'Decidir' }],
    },
  },

  {
    slug: 'knowledge-os-presentation', type: 'TechArticle', tier: 'S', hasMd: true,
    title: 'Knowledge OS Enterprise — Arquitetura IA-First de Conhecimento',
    headline: 'Knowledge OS Enterprise: conhecimento corporativo como infraestrutura cognitiva governada',
    description: 'Plataforma IA-First de conhecimento corporativo: GraphRAG, governança federada, Spec-Driven Development, observabilidade cognitiva, FinOps e Índice de Reuso.',
    datePublished: '2026-05-07', dateModified: '2026-06-21',
    section: 'Arquitetura Enterprise',
    tags: ['Knowledge OS', 'GraphRAG', 'Knowledge Graph', 'AI-First', 'FinOps de IA'],
    keywords: ['Knowledge OS', 'GraphRAG', 'Knowledge Graph', 'SDD', 'AI-First', 'observabilidade cognitiva', 'FinOps de IA', 'circuit breakers', 'índice de reuso', 'governança de conhecimento'],
    about: [
      { name: 'Knowledge Graph' }, { name: 'GraphRAG' }, { name: 'Spec-Driven Development' },
      { name: 'Governança de Conhecimento Corporativo' }, { name: 'FinOps de IA' },
    ],
    audience: 'C-Level, VP Engineering, Heads of Architecture, Knowledge Engineers, Platform Teams',
    tldr: {
      heading: 'O que é o Knowledge OS Enterprise',
      lede: 'O **Knowledge OS** trata o conhecimento corporativo como **infraestrutura cognitiva governada**, não como um repositório passivo de documentos. É uma plataforma IA-First que combina grafo de conhecimento, recuperação aumentada e governança para que decisões sejam mais rápidas e a IA opere com segurança.',
      points: [
        '**GraphRAG** — recuperação aumentada sobre um Knowledge Graph, não só busca semântica plana.',
        '**Spec-Driven Development** — a intenção governada vive em especificações versionadas.',
        '**Observabilidade cognitiva + Circuit Breakers** — visibilidade e contenção do comportamento da IA.',
        '**FinOps + Índice de Reuso** — custo sob controle e conhecimento que se reaproveita em vez de reprocessar.',
      ],
      foot: 'Arquitetura enterprise alinhada à [Engenharia da Confiança](/engenharia-confianca).',
    },
    faq: [
      { q: 'O que é o Knowledge OS?', a: 'É uma plataforma IA-First que trata o conhecimento corporativo como infraestrutura cognitiva governada: grafo de conhecimento, recuperação aumentada (GraphRAG), governança federada e observabilidade. O objetivo é acelerar decisões mantendo a IA segura e auditável.' },
      { q: 'O que é GraphRAG e por que usar?', a: 'GraphRAG é recuperação aumentada (RAG) ancorada num Knowledge Graph em vez de só embeddings planos. As relações explícitas do grafo dão contexto estruturado à IA, reduzindo alucinação e melhorando a rastreabilidade das respostas.' },
      { q: 'Como o Knowledge OS controla custo e risco da IA?', a: 'Com FinOps para IA (ledgers de quota e orçamento explícito), Circuit Breakers cognitivos que contêm comportamento anômalo e um Índice de Reuso que premia reaproveitar conhecimento em vez de reprocessar — reduzindo gasto e deriva.' },
      { q: 'O que é observabilidade cognitiva?', a: 'É a visibilidade sobre como a IA chega às respostas — quais fontes, quais inferências, qual confiança — para que outputs em produção sejam auditáveis e governáveis, e não caixas-pretas.' },
    ],
    mdSections: [
      { h: 'Conhecimento como infraestrutura', body: 'O Knowledge OS muda o conhecimento de repositório passivo para infraestrutura cognitiva governada: versionada (SDD), observável (observabilidade cognitiva), contida (Circuit Breakers) e econômica (FinOps + Índice de Reuso). É a base para decisões mais rápidas com IA segura.' },
    ],
    og: {
      eyebrow: 'Arquitetura IA-First',
      title: 'Knowledge {OS} Enterprise',
      subtitle: 'Conhecimento como infraestrutura cognitiva governada',
      thesis: 'Decisões mais rápidas, IA com segurança.',
      chips: [{ k: 'GRAPH', label: 'GraphRAG' }, { k: 'SDD', label: 'Intenção' }, { k: 'OBS', label: 'Cognitiva' }, { k: 'FINOPS', label: 'Reuso' }],
    },
  },

  // ===================================================================== TIER A
  {
    slug: 'salesforce-agentic-dev', type: 'TechArticle', tier: 'A', hasMd: true,
    title: 'Desenvolver Salesforce com IA Agentic sem gerar débito técnico',
    description: 'Guia prático de desenvolvimento Salesforce com IA agêntica sem dívida técnica: Spec-Driven Development, Devin (Cognition), Flosum CLI, Modelo Federado e Salesforce CLI.',
    datePublished: '2026-04-20', dateModified: '2026-06-21',
    section: 'Salesforce · DevOps', tags: ['Salesforce', 'Devin', 'Flosum', 'Spec-Driven Development', 'DevOps'],
    keywords: ['Salesforce', 'IA agêntica', 'débito técnico', 'Spec-Driven Development', 'Devin', 'Flosum CLI', 'Modelo Federado', 'Salesforce CLI', 'Apex', 'governança'],
    about: [{ name: 'Salesforce' }, { name: 'Agentic DevOps' }, { name: 'Spec-Driven Development' }, { name: 'Devin' }],
    audience: 'Desenvolvedores Salesforce, Tech Leads, Arquitetos de Plataforma',
    tldr: {
      heading: 'Desenvolver Salesforce com IA agêntica sem débito técnico',
      lede: 'Usar IA agêntica no Salesforce **sem acumular dívida técnica** exige método: a IA implementa contra uma **especificação versionada**, não contra prompts soltos, e cada mudança passa por governança e validação automática antes do deploy.',
      points: [
        '**Spec-Driven Development** — a spec é a fonte da verdade; Devin implementa contra ela.',
        '**Modelo Federado** — autonomia das squads com governança central via Flosum CLI.',
        '**Validação automática** — Apex Tests e gates provam a intenção antes de promover.',
        '**Salesforce CLI + Git** — o estado de metadados versionado e auditável.',
      ],
      foot: 'Operacionaliza os princípios da [Engenharia de Agentes de IA](/engenharia-agentes-ia).',
    },
    faq: [
      { q: 'Como usar IA agêntica no Salesforce sem gerar débito técnico?', a: 'Fazendo a IA implementar contra uma especificação versionada (Spec-Driven Development) em vez de prompts soltos, e validando cada mudança com Apex Tests e gates antes do deploy. A dívida técnica nasce de gerar código sem contrato; o método troca o "torça para funcionar" por intenção auditável.' },
      { q: 'O que é o Modelo Federado de desenvolvimento?', a: 'É um arranjo que dá autonomia às squads para entregar rápido, mantendo governança central sobre qualidade e segurança (via Flosum CLI e políticas comuns). Descentraliza a execução sem descentralizar o risco.' },
      { q: 'Qual o papel do Devin nesse fluxo?', a: 'Devin é o agente que executa a implementação contra a spec: descobre o contexto relevante, edita o metadado/Apex e roda os testes. O humano atua como Orquestrador Cognitivo, definindo intenção e julgando o resultado.' },
      { q: 'Como o Flosum e o Salesforce CLI entram?', a: 'O Salesforce CLI versiona o estado de metadados no Git, tornando cada mudança rastreável; o Flosum CLI aplica a governança (aprovações, políticas, promoção entre ambientes) sobre essa esteira. Juntos garantem velocidade com controle.' },
    ],
    mdSections: [{ h: 'Por que a dívida técnica aparece', body: 'Dívida técnica com IA surge quando se gera código sem contrato e sem validação — bonito na demo, frágil em produção. O antídoto é Spec-Driven Development com gates automáticos: a IA implementa contra a spec e nada é promovido sem prova de que a intenção foi cumprida.' }],
    og: { eyebrow: 'Salesforce · Agentic DevOps', title: 'Salesforce com {IA Agentic}', subtitle: 'Sem gerar débito técnico', thesis: 'A spec é a fonte da verdade; o deploy é governado.', chips: [{ k: 'SPEC', label: 'SDD' }, { k: 'DEVIN', label: 'Execução' }, { k: 'FLOSUM', label: 'Governança' }, { k: 'TESTS', label: 'Validação' }] },
  },

  {
    slug: 'salesforce-agentic-quickstart', type: 'TechArticle', tier: 'A', hasMd: true,
    title: 'Quick Start — Salesforce + Devin + Flosum em menos de 60 minutos',
    description: 'Do zero ao primeiro deploy governado em menos de 60 minutos: repositório configurado, especificação escrita e Devin executando no seu contexto Salesforce.',
    datePublished: '2026-04-22', dateModified: '2026-06-21',
    section: 'Salesforce · DevOps', tags: ['Salesforce', 'Devin', 'Flosum', 'Quick Start', 'Onboarding'],
    keywords: ['Salesforce', 'Devin', 'Flosum', 'quick start', 'Spec-Driven Development', 'deploy governado', 'onboarding', 'repositório'],
    about: [{ name: 'Salesforce' }, { name: 'Devin' }, { name: 'Spec-Driven Development' }],
    audience: 'Desenvolvedores e Squads Salesforce iniciando com IA agêntica',
    tldr: {
      heading: 'Do zero ao primeiro deploy governado em <60 min',
      lede: 'Um caminho guiado para sair do **zero ao repositório configurado**, com a primeira especificação escrita e o **Devin executando no seu contexto Salesforce** em menos de uma hora — já dentro de uma esteira governada.',
      points: [
        '**Repositório configurado** — metadados Salesforce versionados no Git.',
        '**Spec escrita** — o primeiro comportamento descrito como fonte da verdade.',
        '**Devin executando** — agente operando no seu contexto, contra a spec.',
        '**Deploy governado** — promoção com governança Flosum desde o primeiro dia.',
      ],
      foot: 'Ponto de partida prático para a [Agentic DevOps](/salesforce-agentic-dev).',
    },
    faq: [
      { q: 'Quanto tempo leva o quick start?', a: 'Menos de 60 minutos do zero ao primeiro deploy governado: configurar o repositório, escrever a primeira especificação e ter o Devin executando no seu contexto Salesforce.' },
      { q: 'O que preciso ter antes de começar?', a: 'Acesso ao org Salesforce, ao repositório Git e às credenciais do Devin e do Flosum. O quick start cobre a configuração inicial e a primeira spec de exemplo.' },
      { q: 'O resultado já é seguro para produção?', a: 'O fluxo já nasce governado: o deploy passa pela esteira do Flosum com aprovações e validação. O quick start estabelece esse trilho desde a primeira entrega, evitando o "deploy manual sem rastro".' },
    ],
    og: { eyebrow: 'Salesforce · Quick Start', title: 'Salesforce + {Devin} + Flosum', subtitle: 'Do zero ao deploy governado em < 60 min', chips: [{ k: '1', label: 'Repositório' }, { k: '2', label: 'Spec' }, { k: '3', label: 'Devin' }, { k: '4', label: 'Deploy' }] },
  },

  {
    slug: 'devops-salesforce', type: 'TechArticle', tier: 'A', hasMd: true,
    title: 'DevOps para Salesforce — Governança, Código e IA',
    description: 'Transforme sua esteira de DevOps Salesforce combinando a governança do Flosum, a flexibilidade do GitHub e a velocidade autônoma do Devin AI.',
    datePublished: '2026-04-10', dateModified: '2026-06-21',
    section: 'Salesforce · DevOps', tags: ['Salesforce', 'DevOps', 'Flosum', 'GitHub', 'Devin'],
    keywords: ['DevOps Salesforce', 'Flosum', 'GitHub', 'Devin AI', 'esteira de deploy', 'governança', 'CI/CD'],
    about: [{ name: 'DevOps para Salesforce' }, { name: 'Flosum' }, { name: 'GitHub' }, { name: 'Devin' }],
    audience: 'Líderes de Engenharia, Arquitetos e Squads Salesforce',
    tldr: {
      heading: 'A evolução do DevOps Salesforce',
      lede: 'A esteira moderna de DevOps Salesforce une três forças: a **governança do Flosum**, a **flexibilidade do GitHub** e a **velocidade autônoma do Devin**. O resultado é entregar rápido sem abrir mão de controle e rastreabilidade.',
      points: [
        '**Governança (Flosum)** — políticas, aprovações e promoção entre ambientes.',
        '**Flexibilidade (GitHub)** — código e metadados versionados, PRs e revisão.',
        '**Velocidade (Devin)** — execução autônoma guiada por especificação.',
        '**Rastreabilidade** — cada mudança tem origem, contrato e prova.',
      ],
    },
    faq: [
      { q: 'Como modernizar a esteira de DevOps no Salesforce?', a: 'Combinando governança (Flosum), versionamento e revisão (GitHub) e execução autônoma guiada por spec (Devin). A chave é tratar metadados como código versionado e promover só o que passou por governança e validação.' },
      { q: 'Por que combinar Flosum, GitHub e Devin?', a: 'Cada um cobre uma dimensão: Flosum traz governança e controle de release; GitHub traz flexibilidade de código e colaboração; Devin traz velocidade autônoma. Juntos entregam rapidez com segurança, sem escolher entre uma e outra.' },
      { q: 'Isso elimina o deploy manual?', a: 'Sim — substitui o deploy manual e sem rastro por uma esteira governada e auditável, em que a promoção entre ambientes segue políticas e cada mudança tem histórico.' },
    ],
    og: { eyebrow: 'Salesforce · DevOps', title: 'DevOps {Salesforce}', subtitle: 'Governança, Código e IA na mesma esteira', chips: [{ k: 'FLOSUM', label: 'Governança' }, { k: 'GITHUB', label: 'Código' }, { k: 'DEVIN', label: 'Velocidade' }, { k: 'CI/CD', label: 'Esteira' }] },
  },

  {
    slug: 'service-operations-2-0', type: 'Article', tier: 'A', hasMd: true,
    title: 'Service Operations 2.0 — Resiliência Sistêmica',
    description: 'O modelo Service Operations 2.0 para o conselho executivo: transformar operações legadas com automação, IA e governança ágil para conquistar e reter clientes.',
    datePublished: '2026-03-15', dateModified: '2026-06-21',
    section: 'Operações · Estratégia', tags: ['Service Operations', 'Resiliência', 'Automação', 'IA', 'Governança'],
    keywords: ['Service Operations 2.0', 'resiliência sistêmica', 'automação', 'IA', 'governança ágil', 'operações legadas', 'experiência do cliente'],
    about: [{ name: 'Service Operations' }, { name: 'Resiliência Sistêmica' }, { name: 'Automação' }],
    audience: 'C-Level, Conselho Executivo, Líderes de Operações',
    tldr: {
      heading: 'O que é Service Operations 2.0',
      lede: '**Service Operations 2.0** é um modelo de operação que troca o combate reativo a incidentes por **resiliência sistêmica**: automação, IA e governança ágil transformam operações legadas em uma capacidade de conquistar e reter clientes.',
      points: [
        '**Resiliência sistêmica** — o sistema absorve falhas em vez de colapsar a cada incidente.',
        '**Automação + IA** — reduz toil e antecipa problemas antes do cliente sentir.',
        '**Governança ágil** — controle sem burocracia que trava a entrega.',
        '**Foco no cliente** — operação como alavanca de conquista, não só de custo.',
      ],
    },
    faq: [
      { q: 'O que é Service Operations 2.0?', a: 'É um modelo que evolui a operação de serviço do combate reativo a incidentes para a resiliência sistêmica, usando automação, IA e governança ágil. O objetivo é transformar operações legadas em uma vantagem competitiva de experiência do cliente.' },
      { q: 'Como ele difere da operação tradicional?', a: 'A operação tradicional reage a incidentes; a 2.0 projeta o sistema para absorver falhas e antecipar problemas. Em vez de medir só custo e uptime, mede impacto no cliente e capacidade de recuperação.' },
      { q: 'Qual o papel da IA e da automação?', a: 'Reduzir o trabalho repetitivo (toil), detectar padrões de risco antes do impacto e acelerar a resposta. A IA entra como apoio governado à decisão, não como caixa-preta no caminho crítico.' },
    ],
    og: { eyebrow: 'Operações · Visão Executiva', title: 'Service {Operations 2.0}', subtitle: 'Resiliência sistêmica para conquistar clientes', chips: [{ k: 'RESIL.', label: 'Sistêmica' }, { k: 'AUTO', label: 'Automação' }, { k: 'IA', label: 'Antecipa' }, { k: 'GOV', label: 'Ágil' }] },
  },

  {
    slug: 'sustentacao', type: 'Article', tier: 'A', hasMd: true,
    title: 'Do Caos à Resiliência — Sustentação de Sistemas em Produção',
    description: 'Jornada prática sobre incidentes, confiabilidade, comunicação e tomada de decisão em ambientes críticos de produção.',
    datePublished: '2026-02-20', dateModified: '2026-06-21',
    section: 'SRE · Confiabilidade', tags: ['Sustentação', 'SRE', 'Incidentes', 'Confiabilidade', 'Produção'],
    keywords: ['sustentação de sistemas', 'SRE', 'gestão de incidentes', 'confiabilidade', 'produção', 'comunicação de crise', 'tomada de decisão'],
    about: [{ name: 'Site Reliability Engineering' }, { name: 'Gestão de Incidentes' }, { name: 'Confiabilidade' }],
    audience: 'Engenheiros de Sustentação, SREs, Líderes de Operação',
    tldr: {
      heading: 'Do caos à resiliência em produção',
      lede: 'Sustentar sistemas críticos é mais do que apagar incêndios: é uma disciplina de **confiabilidade, comunicação e decisão sob pressão**. A jornada vai do caos reativo à resiliência, onde incidentes viram aprendizado e o sistema fica mais forte a cada falha.',
      points: [
        '**Incidentes como sinal** — cada falha revela uma fragilidade a corrigir na raiz.',
        '**Confiabilidade mensurável** — SLIs/SLOs no lugar do "parece estável".',
        '**Comunicação de crise** — clareza e cadência reduzem o dano colateral.',
        '**Decisão sob pressão** — critérios definidos antes evitam o pânico no incidente.',
      ],
    },
    faq: [
      { q: 'O que é sustentação de sistemas em produção?', a: 'É a disciplina de manter sistemas críticos confiáveis em operação: prevenir, detectar e responder a incidentes, medir confiabilidade (SLIs/SLOs) e aprender com cada falha para fortalecer o sistema. Vai além do suporte reativo — é engenharia de confiabilidade.' },
      { q: 'Como sair do caos reativo?', a: 'Trocando o heroísmo individual por método: instrumentar confiabilidade com métricas, definir critérios de decisão antes do incidente, padronizar a comunicação de crise e tratar cada incidente como aprendizado que corrige a causa-raiz.' },
      { q: 'Por que comunicação importa tanto num incidente?', a: 'Porque grande parte do dano de um incidente é colateral — clientes, times e liderança no escuro. Comunicação clara e com cadência definida contém a ansiedade, alinha a resposta e preserva a confiança enquanto o problema é resolvido.' },
    ],
    og: { eyebrow: 'SRE · Confiabilidade', title: 'Do Caos à {Resiliência}', subtitle: 'Sustentação de sistemas críticos em produção', chips: [{ k: 'INC.', label: 'Sinal' }, { k: 'SLO', label: 'Confiabilidade' }, { k: 'COMMS', label: 'Crise' }, { k: 'DEC.', label: 'Sob pressão' }] },
  },

  {
    slug: 'socialselling', type: 'TechArticle', tier: 'A', hasMd: true,
    title: 'SocialSelling — Busca de clientes mais eficiente com IA',
    description: 'Overview do projeto SocialSelling: arquitetura, especificações (ADRs/SDDs), boas práticas (SDD-to-Code Loop, gates, determinismo, Open-World) e aprendizado por feedback.',
    datePublished: '2026-03-01', dateModified: '2026-06-21',
    section: 'IA · Vendas', tags: ['Social Selling', 'IA', 'Spec-Driven Development', 'Determinismo', 'ADR'],
    keywords: ['social selling', 'prospecção com IA', 'ADR', 'SDD', 'SDD-to-Code Loop', 'gates', 'determinismo', 'Open-World', 'aprendizado por feedback'],
    about: [{ name: 'Social Selling' }, { name: 'Spec-Driven Development' }, { name: 'Determinismo' }],
    audience: 'Times de Vendas, Engenheiros de IA, Líderes Comerciais',
    tldr: {
      heading: 'O que é o SocialSelling',
      lede: 'O **SocialSelling** torna a busca de clientes **mais eficiente e automática com IA**, construído com engenharia de verdade: decisões registradas em **ADRs/SDDs**, um **SDD-to-Code Loop** com gates determinísticos e aprendizado contínuo por feedback.',
      points: [
        '**Prospecção automática com IA** — encontra e qualifica clientes com menos esforço manual.',
        '**ADRs/SDDs** — arquitetura e comportamento documentados como fonte da verdade.',
        '**SDD-to-Code Loop + gates** — determinismo e Open-World no caminho crítico.',
        '**Aprendizado por feedback** — o sistema melhora com o resultado real.',
      ],
    },
    faq: [
      { q: 'O que é o projeto SocialSelling?', a: 'É um sistema que torna a busca e a qualificação de clientes mais eficientes e automáticas com IA. Foi construído com engenharia disciplinada: decisões em ADRs/SDDs, um loop SDD-to-Code com gates determinísticos e aprendizado por feedback.' },
      { q: 'Como o determinismo e o Open-World aparecem aqui?', a: 'O caminho crítico resolve o que dá para resolver com regras (determinístico-primeiro) e trata ausência de dado como incerteza explícita (Open-World), não como "falso". Isso evita que a IA invente qualificações e mantém o resultado auditável.' },
      { q: 'O que é o SDD-to-Code Loop?', a: 'É o ciclo em que a especificação dirige a implementação e os gates validam cada passo antes de avançar: escreve-se a intenção, a IA implementa contra ela e os testes/gates provam a conformidade. O aprendizado por feedback realimenta a spec.' },
    ],
    og: { eyebrow: 'IA · Vendas', title: 'Social{Selling}', subtitle: 'Busca de clientes eficiente e automática com IA', chips: [{ k: 'ADR', label: 'Decisões' }, { k: 'SDD', label: 'Loop' }, { k: 'GATES', label: 'Determinismo' }, { k: 'FBK', label: 'Aprende' }] },
  },

  {
    slug: 'proposta-observabilidade-mobile', type: 'TechArticle', tier: 'A', hasMd: true,
    title: 'Observabilidade SRE para Mobilidade Corporativa',
    description: 'Arquitetura de Observabilidade SRE para mobilidade corporativa com Datadog, Azure e Android Enterprise: visibilidade fim a fim da frota de dispositivos.',
    datePublished: '2026-03-10', dateModified: '2026-06-21',
    section: 'SRE · Observabilidade', tags: ['Observabilidade', 'SRE', 'Datadog', 'Azure', 'Android Enterprise'],
    keywords: ['observabilidade SRE', 'mobilidade corporativa', 'Datadog', 'Azure', 'Android Enterprise', 'frota de dispositivos', 'telemetria', 'MDM'],
    about: [{ name: 'Observabilidade' }, { name: 'Site Reliability Engineering' }, { name: 'Android Enterprise' }],
    audience: 'SREs, Arquitetos de Infraestrutura, Líderes de TI/Mobilidade',
    tldr: {
      heading: 'Observabilidade SRE para mobilidade corporativa',
      lede: 'Uma arquitetura de **observabilidade fim a fim** para frotas de dispositivos corporativos, unindo **Datadog, Azure e Android Enterprise** para transformar uma frota opaca em telemetria acionável — e reduzir o tempo de detecção e resolução de problemas em campo.',
      points: [
        '**Visibilidade fim a fim** — do dispositivo à nuvem, numa só visão.',
        '**Datadog** — métricas, logs e traces correlacionados.',
        '**Azure + Android Enterprise** — identidade, gestão (MDM) e telemetria da frota.',
        '**Menor MTTR** — detectar e resolver antes do impacto no usuário.',
      ],
    },
    faq: [
      { q: 'O que é observabilidade SRE para mobilidade corporativa?', a: 'É a capacidade de enxergar, de ponta a ponta, a saúde de uma frota de dispositivos corporativos — do aparelho à nuvem — com métricas, logs e traces correlacionados. O objetivo é detectar e resolver problemas em campo antes que afetem o usuário.' },
      { q: 'Por que Datadog, Azure e Android Enterprise juntos?', a: 'O Datadog correlaciona métricas, logs e traces; o Azure provê identidade e backend; o Android Enterprise gerencia a frota (MDM) e expõe telemetria dos dispositivos. Integrados, dão uma visão única e acionável da frota.' },
      { q: 'Que resultado a arquitetura entrega?', a: 'Redução do tempo de detecção e de resolução (MTTR) de incidentes em campo, menos pontos cegos na frota e decisões operacionais baseadas em telemetria real em vez de suposição.' },
    ],
    og: { eyebrow: 'SRE · Observabilidade', title: 'Observabilidade {SRE} Mobile', subtitle: 'Mobilidade corporativa com Datadog, Azure e Android', chips: [{ k: 'DDOG', label: 'Telemetria' }, { k: 'AZURE', label: 'Backend' }, { k: 'ANDROID', label: 'Frota' }, { k: 'MTTR', label: 'Menor' }] },
  },

  {
    slug: 'proposta', type: 'Article', tier: 'A', hasMd: true,
    title: 'Inteligência de Vendas em Tempo Real — Salesforce + AWS',
    description: 'Proposta de inteligência de vendas em tempo real combinando Salesforce e AWS para revolucionar a eficiência comercial com dados e IA.',
    datePublished: '2026-02-01', dateModified: '2026-06-21',
    section: 'IA · Vendas', tags: ['Salesforce', 'AWS', 'Inteligência de Vendas', 'Tempo Real', 'IA'],
    keywords: ['inteligência de vendas', 'tempo real', 'Salesforce', 'AWS', 'eficiência comercial', 'dados', 'IA', 'eventos'],
    about: [{ name: 'Inteligência de Vendas' }, { name: 'Salesforce' }, { name: 'AWS' }],
    audience: 'Líderes Comerciais, Diretores de Vendas, Arquitetos de Dados',
    tldr: {
      heading: 'Inteligência de vendas em tempo real',
      lede: 'Uma arquitetura que combina **Salesforce e AWS** para levar **inteligência de vendas em tempo real** ao time comercial: eventos e dados processados na hora viram sinais acionáveis, elevando a eficiência da operação de vendas.',
      points: [
        '**Tempo real** — eventos processados na hora, não em relatórios do dia seguinte.',
        '**Salesforce + AWS** — o CRM como cérebro comercial, a nuvem como motor de dados.',
        '**Sinais acionáveis** — a próxima melhor ação no momento certo.',
        '**Eficiência comercial** — menos esforço manual, mais conversão.',
      ],
    },
    faq: [
      { q: 'O que é inteligência de vendas em tempo real?', a: 'É a capacidade de transformar eventos e dados de vendas em sinais acionáveis no momento em que acontecem, em vez de depender de relatórios atrasados. Combinando Salesforce e AWS, o time recebe a próxima melhor ação na hora certa.' },
      { q: 'Como Salesforce e AWS se complementam?', a: 'O Salesforce é o cérebro comercial (CRM, processos e contexto do cliente); a AWS provê o motor de dados e eventos em tempo real (ingestão, processamento e IA). Juntos entregam decisões comerciais baseadas em dados atuais.' },
      { q: 'Qual o ganho para a operação comercial?', a: 'Mais eficiência: menos trabalho manual de garimpar dados, priorização automática das melhores oportunidades e ação no momento de maior probabilidade de conversão.' },
    ],
    og: { eyebrow: 'IA · Vendas', title: 'Inteligência de {Vendas} em Tempo Real', subtitle: 'Salesforce + AWS para eficiência comercial', chips: [{ k: 'RT', label: 'Tempo real' }, { k: 'SFDC', label: 'CRM' }, { k: 'AWS', label: 'Dados' }, { k: 'AÇÃO', label: 'Sinais' }] },
  },

  // ===================================================================== TIER B
  {
    slug: 'index', type: 'ProfilePage', tier: 'B', hasMd: false, ogType: 'website',
    title: 'Maurício Yokoyama Issei — Tech Lead & Arquiteto de Soluções de IA',
    description: 'Tech Lead com mais de 20 anos em desenvolvimento de software e liderança técnica, com foco em soluções robustas em Salesforce, AWS, APIs e Engenharia de IA.',
    datePublished: '2026-01-10', dateModified: '2026-06-21',
    keywords: ['Maurício Yokoyama Issei', 'Tech Lead', 'Arquiteto de Soluções', 'Salesforce', 'AWS', 'APIs', 'Engenharia de IA', 'SRE'],
    og: { eyebrow: 'Tech Lead · Arquiteto de IA', title: 'Maurício {Yokoyama Issei}', subtitle: '20+ anos: Salesforce, AWS, APIs e Engenharia de IA' },
  },
  {
    slug: 'catalogo', type: 'CollectionPage', tier: 'B', hasMd: false, ogType: 'website',
    title: 'Catálogo · Mapa do Ecossistema',
    description: 'O mapa do ecossistema de Maurício Issei: uma jornada em cinco pilares — Mentalidade, Método, Aplicação, Valor e Resultados — conectando artigos, propostas técnicas e experiências.',
    datePublished: '2026-01-15', dateModified: '2026-06-21',
    keywords: ['catálogo', 'Maurício Issei', 'engenharia de IA', 'Salesforce', 'propostas técnicas'],
    itemList: [
      { name: 'A Engenharia da Confiança', url: 'https://mauricio.issei.com.br/engenharia-confianca' },
      { name: 'Engenharia de Agentes de IA', url: 'https://mauricio.issei.com.br/engenharia-agentes-ia' },
      { name: 'Vibe Coding com Devin', url: 'https://mauricio.issei.com.br/devin' },
      { name: 'Engenharia Reversa Assistida por IA', url: 'https://mauricio.issei.com.br/proposta-engenharia-reversa' },
      { name: 'Knowledge OS Enterprise', url: 'https://mauricio.issei.com.br/knowledge-os-presentation' },
      { name: 'Agentic DevOps for Salesforce', url: 'https://mauricio.issei.com.br/salesforce-agentic-dev' },
      { name: 'Service Operations 2.0', url: 'https://mauricio.issei.com.br/service-operations-2-0' },
      { name: 'Do Caos à Resiliência — Sustentação', url: 'https://mauricio.issei.com.br/sustentacao' },
    ],
    og: { eyebrow: 'Catálogo · Mapa do Ecossistema', title: 'Mapa do {Ecossistema}', subtitle: 'Mentalidade · Método · Aplicação · Valor · Resultados' },
  },
  {
    slug: 'life', type: 'AboutPage', tier: 'B', hasMd: false, ogType: 'website',
    title: 'A Jornada de Maurício Issei — Narrativa Interativa em Pixel Art',
    description: 'A trajetória de vida e carreira de Maurício Issei numa experiência interativa em Pixel Art: uma viagem visual de 1982 aos dias de hoje — tecnologia, família e evolução.',
    datePublished: '2026-01-20', dateModified: '2026-06-21',
    keywords: ['Maurício Issei', 'jornada', 'narrativa interativa', 'pixel art', 'trajetória', 'carreira'],
    og: { eyebrow: 'Narrativa · Pixel Art', title: 'A {Jornada} de Maurício Issei', subtitle: 'De 1982 aos dias de hoje: tecnologia, família e evolução' },
  },
  {
    slug: 'life3d', type: 'AboutPage', tier: 'B', hasMd: false, ogType: 'website',
    title: 'Vida em 3D — Maurício Issei',
    description: 'A trajetória de vida de Maurício Issei numa experiência 3D imersiva: uma jornada contemplativa de 1982 aos dias de hoje.',
    datePublished: '2026-01-22', dateModified: '2026-06-21',
    keywords: ['Maurício Issei', 'vida em 3D', 'experiência imersiva', 'WebGL', 'trajetória'],
    og: { eyebrow: 'Experiência 3D Imersiva', title: 'Vida em {3D}', subtitle: 'Uma jornada contemplativa de 1982 aos dias de hoje' },
  },
  {
    slug: 'terminal-evolutivo', type: 'AboutPage', tier: 'B', hasMd: true, ogType: 'website',
    title: 'Terminal Evolutivo — A Jornada de Maurício Issei (1982–2026)',
    headline: 'Terminal Evolutivo: a evolução de um arquiteto, contada por uma página que envelhece ao rolar',
    description: 'Da TV de tubo à IA agêntica: a evolução de Maurício Issei em cinco fases, numa narrativa interativa (HTML semântico + WebGL) cuja estética envelhece conforme você rola.',
    datePublished: '2026-06-22', dateModified: '2026-06-22',
    keywords: ['Maurício Issei', 'jornada', 'scrollytelling', 'narrativa interativa', 'WebGL', 'Three.js', 'Tech Lead', 'Arquiteto de Soluções', 'IA Agêntica', 'trajetória'],
    about: [{ name: 'Maurício Yokoyama Issei' }, { name: 'Trajetória profissional' }, { name: 'Scrollytelling' }, { name: 'WebGL' }],
    audience: 'Recrutadores, Líderes de Engenharia, Pares Técnicos',
    tldr: {
      heading: 'O que é o Terminal Evolutivo',
      lede: 'O **Terminal Evolutivo** conta a evolução de **Maurício Issei** de 1982 a 2026 em **cinco fases** — de espectador a operador a arquiteto/mentor — numa página de *scrollytelling* cuja **estética envelhece conforme você rola** (terminal CRT → wireframe → rede de dados → blocos corporativos → rede neural).',
      points: [
        '**Cinco fases** alinhadas aos arcos de vida: Infância, Treinamento, Rede Discada, Nuvem Corporativa e o Prompt da IA.',
        '**Casos STAR reais** embutidos no fluxo: −R$3MM no contrato Salesforce, +15% nas metas com a Pipe Automática, 10 dias → tempo real no Agrupamento.',
        '**Marco do Arquiteto** — a virada de Analista para Arquiteto: "desenhar sistemas eu já fazia; agora desenho a inteligência — e os times — que os operam".',
        '**Arquitetura híbrida** — foreground HTML semântico (a11y/SEO) sobre fundo WebGL, com fallback acessível sem WebGL/JS.',
      ],
      foot: 'Veja também o [currículo completo](/index.html) e o [mapa do ecossistema](/catalogo.html).',
    },
    faq: [
      { q: 'O que é o Terminal Evolutivo?', a: 'É uma página de portfólio em scrollytelling que conta a evolução de Maurício Issei de 1982 a 2026 em cinco fases. O diferencial é que a própria estética da página evolui conforme o usuário rola, espelhando a maturidade tecnológica de cada época — de um terminal analógico a uma rede neural holográfica.' },
      { q: 'Quais resultados de carreira a página destaca?', a: 'Casos reais com impacto mensurável: economia de mais de R$3 milhões na renegociação do contrato Salesforce (2020), aumento de mais de 15% no atingimento de metas com a Pipe Automática (2025) e a redução do SLA de Agrupamento Comercial de 10 dias para tempo real (2024). Somam-se 20+ anos em tecnologia e 15+ em grandes empresas.' },
      { q: 'A página funciona sem WebGL ou JavaScript?', a: 'Sim. O conteúdo é HTML semântico linear e legível por leitores de tela; o fundo 3D (WebGL/Three.js) é progressive enhancement puramente decorativo. Sem WebGL ou sem JavaScript, a página exibe um fundo sólido por tema e todo o conteúdo permanece intacto e indexável.' },
    ],
    terms: [
      { slug: 'scrollytelling', name: 'Scrollytelling', def: 'Narrativa cuja progressão visual é controlada pelo scroll do usuário.' },
      { slug: 'progressive-enhancement', name: 'Progressive enhancement', def: 'Camada extra (WebGL) que enriquece a experiência sem ser pré-requisito do conteúdo.' },
      { slug: 'morphing-semantico', name: 'Morphing semântico', def: 'Transição contínua entre cenas 3D interpolando um único sistema de partículas, sem fade.' },
      { slug: 'marco-do-arquiteto', name: 'Marco do Arquiteto', def: 'Beat narrativo da virada de Analista para Arquiteto: desenhar sistemas em vez de só construí-los.' },
    ],
    mdSections: [
      { h: 'As cinco fases', body: 'A jornada se divide em cinco eras visuais: 1) Terminal Analógico (1982–1994, infância e os heróis japoneses); 2) O Treinamento (1995–1999, adolescência e o primeiro computador); 3) A Rede Discada (2000–2009, início da carreira em Java e a virada de operador a analista); 4) A Nuvem Corporativa (2010–2019, família, liderança técnica e os primeiros grandes resultados na Rede); 5) O Prompt da IA (2020–2026, maturidade, arquitetura de soluções e foco em IA agêntica).' },
      { h: 'Arquitetura técnica', body: 'A página combina foreground HTML semântico (preservando SEO e acessibilidade) com um fundo WebGL em Three.js que morfa continuamente entre cinco estados, dirigido por GSAP ScrollTrigger. A renderização é sob demanda (sem ticker contínuo) e há fallback CSS sólido por tema quando o WebGL não está disponível.' },
    ],
    og: {
      eyebrow: 'Narrativa Interativa · 1982–2026',
      title: 'Terminal {Evolutivo}',
      subtitle: 'A jornada de Maurício Issei: de espectador a arquiteto',
      thesis: 'Uma página que envelhece conforme você rola.',
      chips: [{ k: '82', label: 'Terminal' }, { k: '00', label: 'Rede' }, { k: '10', label: 'Nuvem' }, { k: '20', label: 'IA' }],
    },
  },
  {
    slug: 'know', type: 'Article', tier: 'B', hasMd: false,
    title: 'Navegando na Complexidade — O Fim das Melhores Práticas',
    headline: 'Por que copiar a fórmula do sucesso falha em sistemas complexos',
    description: 'Por que copiar a fórmula do sucesso falha em sistemas complexos: uma reflexão sobre contexto, o framework Cynefin e os limites das "melhores práticas".',
    datePublished: '2026-02-05', dateModified: '2026-06-21',
    section: 'Complexidade', tags: ['Complexidade', 'Cynefin', 'Sistemas Complexos', 'Liderança'],
    keywords: ['complexidade', 'Cynefin', 'melhores práticas', 'sistemas complexos', 'contexto', 'liderança', 'tomada de decisão'],
    about: [{ name: 'Sistemas Complexos' }, { name: 'Cynefin' }, { name: 'Tomada de Decisão' }],
    og: { eyebrow: 'Complexidade · Reflexão', title: 'O Fim das {Melhores Práticas}', subtitle: 'Por que copiar a fórmula do sucesso falha', thesis: 'Em sistemas complexos, o contexto vence a receita.' },
  },
];
